# -*- encoding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Theme Impacto',
    'description': 'Theme Impacto',
    'category': 'Theme/Ecommerce',
    'sequence': 1000,
    'version': '1.1',
    'author': 'Adventumweb',
    'support': 'megatheme@gmail.com',
    'license' : 'OPL-1',
    'depends': ['website', 'website_theme_install', 'sale'],
    'data': [
    'security/ir.model.access.csv',
        'views/assets.xml',
        'views/customize_model.xml',
        'views/HeaderStyle.xml',
        'views/page_homepage.xml',
		'views/page_home-agency.xml',
        'views/page_home-creative-bussiness.xml',
		'views/page_home-corporate.xml',
		'views/page_home-construction.xml',
		'views/page_home-medical.xml',
        'views/page_home-gym.xml',
		'views/page_home-app.xml',
		'views/page_home-education.xml',
        'views/page_home-restaurant.xml',
		'views/page_home-shop.xml',
        'views/page_home-shop-shoes.xml',
        'views/page_home-shop-furniture.xml',
		'views/page_home-fashion.xml',
		'views/page_home-goggle.xml',
		'views/page_home-industry.xml',
		'views/page_home-solar.xml',
		'views/page_home-coffee.xml',
		'views/page_home-drone.xml',
		'views/page_home-landscaping.xml',
		'views/page_home-architecture.xml',
		'views/page_home-transport.xml',
        'views/page_home-spa.xml',
        'views/page_home-pet.xml',
        'views/page_home-kids.xml',
        'views/page_home-delivery.xml',
        'views/page_home-dento.xml',
        'views/page_home-factory.xml',
        'views/page_home-coach.xml',
        'views/page_home-law.xml',
        'views/page_home-lab.xml',
        'views/page_home-moving.xml',
        'views/website_view.xml',
        'views/template.xml',    
        'views/footer.xml',
        'views/snippets.xml',
        'views/snippets_option.xml'
    ],
    'live_test_url': 'http://theme-impacto.adventumweb.com:8070/',
	   #'images': [ 'static/description/priview.jpg','static/description/priview_screenshot.jpg'],
       'images': [
      'static/description/impacto.jpg',
 	  'static/description/impacto_screenshot.jpg'
    ],
    'price': 149.00,
    'currency': 'EUR',
    'application': False
}
